on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master
jobs:
  pre_clean:
    name: pre_clean
    runs-on: self-hosted
    container:
      image: alpine
    steps:
      - name: Cleanup workspace
        if: always()
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true
  build:
    name: build
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Run the copy env script
        run: ./scripts/development/copy_env.sh
        shell: bash
      - name: Docker compose build
        run: ./scripts/development/docker_build.sh
        shell: bash
      - name: Docker compose up
        run: ./scripts/development/docker_up.sh
        shell: bash
      - name: ASP.NET build
        run: ./scripts/development/aspnet_build.sh
        shell: bash
      - name: Docker compose down
        run: ./scripts/development/docker_down.sh
        shell: bash
  post_clean:
    name: post_clean
    runs-on: self-hosted
    container:
      image: alpine
    steps:
      - name: Cleanup workspace
        if: always()
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true
